### ISSUE TITLE
Project/page.tsx bugs 

### ISSUE THREAD

**Issue by Potatooff** [chronark/chronark.com#28]
I ran the project locally and the website works as expected but once i click on project i get this error 

Error: Cannot read properties of undefined (reading 'slug')

```
<div className="flex flex-col w-full gap-8 mx-auto border-t border-gray-900/10 lg:mx-0 lg:border-t-0 ">
						{[top2, top3].map((project) => (
							<Card key={project.slug}>
								<Article project={project} views={views[project.slug] ?? 0} />
							</Card>
						))}
					</div>
```

![image](https://github.com/chronark/chronark.com/assets/112786274/645e3f84-ec6a-4639-b7c9-ba722ec6d4b2)

**Comment by Potatooff** [comment]
I Managed to fix it, hahha, Beautiful Website!

**Comment by TechTyphoon** [comment]
> I Managed to fix it, hahha, Beautiful Website!

how did you do that?

**Comment by Potatooff** [comment]
**Rechecking variables name because i am pretty sure i made a mistake between the text and the variable name**

**Comment by ruwaifatahir** [comment]
@Potatooff Can you please share how exactly you fixed the error? I'm experiencing the same error.
