### ISSUE TITLE
home page text fill color is not full.

### ISSUE THREAD

**Issue by liuxuan30** [chronark/chronark.com#6]
Hi there,

Notice another issue that,

the home page's main title has white fill color, but if the char is like p, or g, the fill is not complete after the animation:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/4375169/235274632-0a3eb67d-c8ac-41b0-82e9-cd7c0b75b010.png">

I tried to tweak the height, but couldn't find which element controls the animation and the final height? it seems there are two lines joining the animation but I cannot see any 'line' element

**Comment by chronark** [comment]
ah that's css, I actually never tried this with characters other than `chronark`. Good catch, I'll take a look

**Comment by daallgeier** [comment]
I actually decided i like that 🙈

**Comment by phuchoangto** [comment]
your project is really amazing!
but hope you fix this soon.

**Comment by dodyagung** [comment]
I have fixed this issue into PR #39 enjoy @liuxuan30 @chronark @daallgeier @phuchoangto

**Comment by chronark** [comment]
Thanks, merged
