### ISSUE TITLE
Code Snippets Contain Ticks

### ISSUE THREAD

**Issue by c0nf1den71al** [chronark/chronark.com#8]
# Code Snippets Contain Ticks

Hey, 

I love your template and have recently started using it, however, I noticed that inline code snippets using the format:
```
`code`
```
contain the back-ticks when rendered:

![image](https://user-images.githubusercontent.com/38860802/236478596-182998b8-5baa-4057-a118-7307dd530338.png)

I have had a play around but no luck - Just wondered if you know what causes this?

Thanks :)

**Comment by chronark** [comment]
Yeah I'm not happy about that either but couldn't fix it
it's coming from tailwind's `prose` class

**Comment by c0nf1den71al** [comment]
Thanks for this. I managed to sort it by updating the tailwind config file. (https://github.com/tailwindlabs/tailwindcss-typography/issues/18#issuecomment-733045571).

I will update this in a pull request now :)
